In [10]:
#python 3 Task1
my_file = open("numbers.txt","w")

for i in (3,45,83,21):
    my_file.write(str(i))
    my_file.write("\n")
#n means write each number on a new line each time
my_file.close()

In [11]:
with open("numbers.txt", "r") as myfile:
    data = myfile.read().replace('\n',',')

    myfile.close()

    print(data)

3,45,83,21,


In [12]:
my_file = open("numbers.txt", "a")

my_file.write("Happy Sunday\n")

my_file.close()

In [4]:
#Python3 Task2
student_mark = int(input("Enter a number"))

if student_mark == 80:
    print("exam grade is A+")
else: 
    print("exam grade is not A+")

exam grade is not A+


In [5]:
target_grade = input("What is your target grade?")
student_mark = input("What is your mark?")
print("student's target grade is " + target_grade + " and mark is " + student_mark + ".")


student's target grade is A and mark is 65.


In [9]:
i = 65
if i > 65:
    print("exam grade is above B.")
elif i == 65:
    print("exam grade is B.")
elif i < 65:
    print("exam grade is below B")

exam grade is B.


In [1]:
#Numpy Task1
import numpy as np

array =  np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [41]:
#Numpy task 2
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
newArray1 = (array1%2 == -1)
print(newArray1)


[False False False False False False False False False]


In [40]:
#Numpy task 3
slice = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(slice[1:10:2])

[ 2  4  6  8 10]


In [29]:
#numpy task4
array1 = np.arange(1,10)
print(array1)


[1 2 3 4 5 6 7 8 9]


In [50]:
#numpy task5
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
newArray = array.reshape(2,5)

print(newArray)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [53]:
#numpy task 6

a = np.arange(3,12).reshape(3,3)
b = np.arange(6,15).reshape(3,3)

print(a)
print(b)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [54]:
a = np.arange(3,12).reshape(3,3)
b = np.arange(6,15).reshape(3,3)
c = np.dot(a,b)

print(c)

[[114 126 138]
 [195 216 237]
 [276 306 336]]


In [56]:
#Numpy Task6
a = np.arange(3,12).reshape(3,3)
b = np.arange(6,15).reshape(3,3)
c = np.dot(a,b)
sum = np.sum(c)

print(sum)

1944


In [60]:
#Extension
my_list = [1, 1, 1]
my_list2 = [2, 2, 2]
my_list3 = [3, 3, 3]
my_list4 = [1, 2, 3]

print(my_list + my_list2 +my_list3 + my_list4 + my_list4 + my_list4)

[1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [75]:

a = np.arange(1,5).reshape(1,1,2)
b = np.arange(4,9).reshape(1,1,2)
print(a)
print(b)


ValueError: cannot reshape array of size 4 into shape (1,1,2)

In [ ]:
c = np.dot(a,b)

print(c)

e = np.sum(c, axis = 0)